package com.example.trackingexpenses.objects

object Fields {
    const val TOTAL_EXPENDITURE = "totalExpenditure"
    const val EXPENSES_FOR_DAY = "expensesForDay"
    const val EXPENSES_FOR_THE_PERIOD = "expensesForThePeriod"
    const val TOTAL_INCOME = "totalIncome"
    const val INCOME_FOR_THE_PERIOD = "incomeForThePeriod"
    const val PERIOD = "period"
    const val DATE_TIME = "dateTime"
    const val TYPE = "type"
    const val CATEGORIES_OF_INCOME = "categoriesOfIncome"
    const val CATEGORIES_OF_EXPENDITURE = "categoriesOfExpenditure"
    const val LAST_ENTER_IN_APP = "lastEnterInApp"
    const val CURRENT_PERIOD = "currentPeriod"
    const val DAY_LIMIT = "dayLimit"
    const val TRANSACTION = "transaction"
    const val PROFILE_TYPE = "profileType"
    const val MEMBERS = "members"
    const val FAMILY_ID = "familyId"
    const val USER_ID = "userId"
    const val STATUS = "status"
    const val NAME = "name"
    const val EMAIL = "email"
    const val IMG = "img"
}